const exerciseList = 
['dumbbell bench press', 
'weighted pushups', 
'dumbbell flyes', 
'incline dumbbell press', 
'low cable crossover',
'decline dumbbell flyes',
'weighted dips',
'wide-Grip decline bench press',
'wide-Grip barbell bench press',
'incline dumbbell flyes',
'cable crossovers',
'decline dumbbell bench press',
'butterflies',
'bench press',
'weighted pull ups',
'v-Bar pulldowns',
'wide-Grip lat pulldown',
'cable row',
'rope straight-Arm pulldown',
't-Bar row',
'reverse grip bent-Over rows',
'bent-Over rows',
'one-Arm dumbbell row',
'deadlift',
'sumo deadlift',
'romanian deadlift',
'single-Leg press',
'leg press',
'squats',
'box squats',
'weighed standing calf raise',
'seated calf raises',
'calf press',
'skullcrusher',
'tricep pushdown',
'weighted bench dip',
'reverse-Grip tricep pushdown',
'tricep dumbbell kickback',
'barbell tricep extension',
'close-Grip bench press',
'smith machine shrugs',
'kettlebell high pulls',
'singe-Arm linear jammer',
'dumbbell front raises',
'seated military press',
'standing military press',
'dumbbell side raises',
'barbell glute bridge',
'barbell hip thrust',
'one-legged cable kickback',
'incline hammer curls',
'wide-Grip standing barbell curls',
'spider curls',
'barbell curls',
'concentration curls',
'preacher curls',
'standing single-Arm curls',
'dumbbell alternate bicep curl'];

export default exerciseList;